---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: redhat-operators-pull-secret
    literals:
      - operator=awx

  - name: awx-admin-password
    type: Opaque
    literals:
      - password=Ansible123!

resources:
  - awx.yaml
  - awx-mesh-ingress.yaml
