- name: Pull, modify, and push a file on Github
  hosts: localhost
  gather_facts: true

  vars:
    git_url: 'https://github.com/raoulaime/awxdev.git'
    new_line: 'This is a new line 20'

  tasks:
    - name: Pull file form a repo
      ansible.builtin.import_role:
        name: manage_git_repo
        tasks_from: pull

    - name: Create file in repo
      ansible.builtin.copy:
        dest: '{{ localrepo }}/time.yml'
        content: '{{ ansible_date_time | to_nice_yaml }}'
        mode: '0664'

    - name: Add new line to file
      ansible.builtin.lineinfile:
        state: present
        path: '{{ file_path }}'
        line: '{{ inventory_hostname_short }}'
        insertafter: "^devserver[0-9]+"
        firstmatch: false
      vars:
        file_path: '{{ localrepo }}/inventories/staging/staginghosts.ini'

    - name: Push file to git repo
      ansible.builtin.import_role:
        name: manage_git_repo
        tasks_from: push
