---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  postgres_storage_class: longhorn
  postgres_data_volume_init: true
  postgres_data_path: /var/lib/pgsql/data/pgdata
  postgres_security_context_settings:
    fsGroup: 26
    fsGroupChangePolicy: Always
    runAsGroup: 26
    runAsNonRoot: true
    runAsUser: 26
    supplementalGroups:
      - 26
  init_postgres_extra_commands: |
    mkdir /var/lib/pgsql/data/userdata
    chown 26:26 /var/lib/pgsql/data/userdata
    chmod 700 /var/lib/pgsql/data/userdata

  ingress_type: ingress
  ingress_hosts:
    - hostname: awx.home.kenitrahub.com
      tls_secret: awx-secret-tls
  ingress_annotations: |
    cert-manager.io/cluster-issuer: letsencrypt-prod
  auto_upgrade: true
  web_replicas: 1
  task_replicas: 1

  task_resource_requirements:
    requests:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: 100M
    limits:
      cpu: 2000m
      memory: 4Gi
      ephemeral-storage: 500M
  web_resource_requirements:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 4Gi
  ee_resource_requirements:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 1000m
      memory: 4Gi
  redis_resource_requirements:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 1000m
      memory: 4Gi
  rsyslog_resource_requirements:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  init_container_resource_requirements:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  postgres_init_container_resource_requirements:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 1000m
      memory: 2Gi
