---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  postgres_storage_class: longhorn
  ingress_type: ingress
  ingress_hosts:
    - hostname: awx.home.kenitrahub.com
      tls_secret: awx-secret-tls
  ingress_annotations: |
    cert-manager.io/issuer: letsencrypt-prod
  web_replicas: 1
  task_replicas: 1

  web_resource_requirements: {}
  task_resource_requirements: {}
  ee_resource_requirements: {}
  init_container_resource_requirements: {}
  postgres_init_container_resource_requirements: {}
  postgres_resource_requirements: {}
  redis_resource_requirements: {}
  rsyslog_resource_requirements: {}
