---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: redhat-operators-pull-secret
    literals:
      - operator=awx

  - name: awx-admin-password
    type: Opaque
    literals:
      - password=Ansible123!

resources:
  - github.com/ansible/awx-operator/config/default?ref=2.12.1
  - awx.yaml

images:
  - name: quay.io/fosterseth/awx-operator
    newTag: 2.12.1
