---
# - include_tasks: unpack.yml

- name: Set repo path
  ansible.builtin.set_fact:
    # git_repo_path: "{{ git_url | regex_search('/(.+).git') | regex_replace('.git', '') }}"
    # localrepopath: "{{ git_url | urlsplit('path') | regex_search('/(.+).git') | regex_replace('.git', '') }}"
    localrepo: "{{ git_url | basename | regex_replace('.git', '') }}"

- name: Debug
  ansible.builtin.debug:
    var: localrepo

- name: Git clone
  block:
    - name: Git Clone
      ansible.builtin.git:
        repo: "{{ git_url }}"
        dest: "{{ playbook_dir }}/{{ localrepo }}"
        accept_hostkey: true
        version: master
        force: true
        # key_file: "{{ git_temp_file.path }}"
      register: git_clone_status

  rescue:
    - name: Remove Created Directory
      ansible.builtin.command: rm -fr '{{ playbook_dir }}/{{ git_repo_path }}'
      args:
        removes: '{{ playbook_dir }}/{{ git_repo_path }}'
      when: not git_clone_status
      changed_when: false

# - include_tasks: cleanup_keys.yml
