---
softwares_list:
  - name: procexp
  - name: putty
  - name: rdcman
  - name: sysinternals
  - name: bginfo

  - name: microsoft-edge
    version: 120.0.2210.91

  - name: notepadplusplus
    version: 8.6.0

  - name: 7zip
    version: 23.1.0

  - name: python
    version: 3.12.1

  - name: adobereader
    version: 2023.8.20458

  - name: sql-server-management-studio
    version: 19.2.56.2

  - name: openssh
    version: 8.6.0-beta1

  - name: vscode
    version: 1.85.1

  - name: powershell-core
    version: 7.4.0

  - name: winscp
    version: 6.1.2
