---
- name: Upgrade installed packages
  chocolatey.chocolatey.win_chocolatey:
    name: all
    state: latest
  register: _upgraded

- name: Show Upgrades
  ansible.builtin.debug:
    var: _upgraded | to_nice_json
